apiVersion: v1
kind: Pod
metadata:
  name: onlinebookstore
  labels:
    app: onlinebookstore
spec:
  containers:
    - name: onlinebookstore
      image: 996622/onlinebookstore:img_tag
      ports:
        - containerPort:8080
